---
title: "Git tutorial"
author: Hiromu Asahina 
date: Febrary 2019 
output: 
  ioslides_presentation:
    slide_level: 2
    widescreen: true
    smaller: true
    toc: true
    number_sections: true
---
<style type="text/css">
.column-left{
  float: left;
  width: 47.5%;
  text-align: left;
}
.column-right{
  float: right;
  width: 47.5%;
  text-align: left;
}
.container{
    display: flex;
}
.left{
    width: 30%;
}
.contents{
    flex: 1;
}
.right{
    width: 30%;
}
pre { 
font-size: 14px;
}
</style>

# Adobe readerをやめてGit+Githubにしたら捗った話

```{r child="./body/introduction.Rmd"}
```

# Git

```{r child="./body/basic.Rmd"}
```

```{r child="./body/single_branch.Rmd"}
```

```{r child="./body/multi_branches.Rmd"}
```

# Github

```{r child="./body/remote_branch.Rmd"}
```

# Taboo and recommended actions

```{r child="./body/taboo_and_recommend.Rmd"}
```

# Conclusion

```{r child="./body/conclusion.Rmd"}
```

# Exercise

```{r child="./body/exercise.Rmd"}
```

# Advanced

```{r child="./body/n_knock.Rmd"}
```

# References 

```{r child="./body/reference.Rmd"}
```



/* # 最初のコミット */

/* # ブロックチェーンとGit */

/* # Gitの名前の由来 */
